
const INIT_QUESTION_MANAGER = "INIT_QUESTION_MANAGER";
const INIT_DB = "INIT_DB";
const INIT_DOCID = "INIT_DOCID";
const INSERT_QUESTION = "INSERT_QUESTION";
const UPDATE_INDICATOR = "UPDATE_INDICATOR";
const UPDATE_QUESTION = "UPDATE_ITEM";
const SETUP_WORKBENCH = "SETUP_WORKBENCH";
const CLEANUP_WORKBENCH = "CLEANUP_WORKBENCH";

export default { INIT_QUESTION_MANAGER, INIT_DB, INIT_DOCID, INSERT_QUESTION, UPDATE_INDICATOR, UPDATE_QUESTION, SETUP_WORKBENCH, CLEANUP_WORKBENCH}
