
const INIT_QUESTION_MANAGER = "INIT_QUESTION_MANAGER";
const INSERT_QUESTION = "INSERT_QUESTION";
const UPDATE_INDICATOR = "UPDATE_INDICATOR";
const UPDATE_QUESTION = "UPDATE_ITEM";

export default { INIT_QUESTION_MANAGER, INSERT_QUESTION, UPDATE_INDICATOR, UPDATE_QUESTION}
